// Export main provider function
export { xai } from "./xai";

// Export error class
export { XaiError } from "./types";

// Export middleware
export { withRetry, withFallback } from "./middleware";
export type { RetryOptions, FallbackOptions } from "./middleware";

// Export all types
export type {
  XaiOptions,
  XaiMessage,
  XaiToolFunction,
  XaiTool,
  XaiToolCall,
  XaiUsage,
  XaiChatChoice,
  XaiChatRequest,
  XaiChatResponse,
  XaiImageGenerateRequest,
  XaiImageEditRequest,
  XaiImageReference,
  XaiGeneratedImage,
  XaiImageResponse,
  XaiVideoGenerateRequest,
  XaiVideoEditRequest,
  XaiVideoExtendRequest,
  XaiVideoReference,
  XaiVideoAsyncResponse,
  XaiVideoData,
  XaiVideoResult,
  XaiFileObject,
  XaiFileListResponse,
  XaiBatchState,
  XaiBatch,
  XaiBatchCreateRequest,
  XaiBatchListResponse,
  XaiBatchListParams,
  XaiBatchRequestMetadata,
  XaiBatchRequestListResponse,
  XaiBatchRequestListParams,
  XaiBatchRequestItem,
  XaiBatchAddRequestsBody,
  XaiBatchResultItem,
  XaiBatchResultListResponse,
  XaiBatchResultListParams,
  XaiChunkConfiguration,
  XaiFieldDefinition,
  XaiCollectionCreateRequest,
  XaiCollection,
  XaiCollectionListParams,
  XaiCollectionListResponse,
  XaiCollectionUpdateRequest,
  XaiDocumentFileMetadata,
  XaiDocument,
  XaiDocumentListParams,
  XaiDocumentListResponse,
  XaiDocumentAddRequest,
  XaiDocumentSearchRequest,
  XaiDocumentSearchMatch,
  XaiDocumentSearchResponse,
  XaiModel,
  XaiModelListResponse,
  XaiLanguageModel,
  XaiLanguageModelListResponse,
  XaiImageGenerationModel,
  XaiImageGenerationModelListResponse,
  XaiVideoGenerationModel,
  XaiVideoGenerationModelListResponse,
  XaiProvider,
  PayloadFieldSchema,
  PayloadSchema,
  ValidationResult,
} from "./types";
