// Export main provider function
export { googleGemini } from "./google-gemini";

// Export error class
export { GeminiError } from "./types";

// Export middleware
export { withRetry, withFallback } from "./middleware";
export type { RetryOptions, FallbackOptions } from "./middleware";

// Export all types
export type {
  GeminiOptions,
  GeminiPart,
  GeminiContent,
  GeminiToolFunctionDeclaration,
  GeminiTool,
  GeminiToolConfig,
  GeminiSafetySetting,
  GeminiGenerationConfig,
  GeminiGenerateContentRequest,
  GeminiSafetyRating,
  GeminiCitationSource,
  GeminiCitationMetadata,
  GeminiGroundingMetadata,
  GeminiCandidate,
  GeminiModalityTokenCount,
  GeminiUsageMetadata,
  GeminiPromptFeedback,
  GeminiGenerateContentResponse,
  GeminiCountTokensRequest,
  GeminiCountTokensResponse,
  GeminiEmbedContentRequest,
  GeminiContentEmbedding,
  GeminiEmbedContentResponse,
  GeminiBatchEmbedContentsRequest,
  GeminiBatchEmbedContentsResponse,
  GeminiPredictRequest,
  GeminiPredictResponse,
  GeminiPredictLongRunningRequest,
  GeminiOperation,
  GeminiBatchGenerateContentRequest,
  GeminiBatchGenerateContentResponse,
  GeminiModel,
  GeminiModelListParams,
  GeminiModelListResponse,
  GeminiFileVideoMetadata,
  GeminiFile,
  GeminiFileUploadRequest,
  GeminiFileUploadResponse,
  GeminiFileCreateRequest,
  GeminiFileListParams,
  GeminiFileListResponse,
  GeminiCachedContent,
  GeminiCachedContentCreateRequest,
  GeminiCachedContentUpdateRequest,
  GeminiCachedContentListParams,
  GeminiCachedContentListResponse,
  GeminiTuningSnapshot,
  GeminiTuningTask,
  GeminiTunedModel,
  GeminiTunedModelCreateRequest,
  GeminiTunedModelUpdateRequest,
  GeminiTunedModelListParams,
  GeminiTunedModelListResponse,
  GeminiTransferOwnershipRequest,
  GeminiPermission,
  GeminiPermissionListParams,
  GeminiPermissionListResponse,
  GeminiBatch,
  GeminiBatchListParams,
  GeminiBatchListResponse,
  GeminiProvider,
  PayloadFieldSchema,
  PayloadSchema,
  ValidationResult,
} from "./types";
