// Export main provider function
export {
  openai,
  textPart,
  imageUrlPart,
  imageBase64Part,
  firstContent,
} from "./openai";

// Export error class
export { OpenAiError } from "./types";

// Export middleware
export {
  withRetry,
  withFallback,
  withRateLimit,
  createRateLimiter,
} from "./middleware";
export type {
  RetryOptions,
  FallbackOptions,
  RateLimiterOptions,
  RateLimiter,
  RateLimitOptions,
} from "./middleware";

// Export all types (request types now flow from zod.ts via types.ts)
export type {
  OpenAiOptions,
  OpenAiMessage,
  OpenAiTextPart,
  OpenAiImageUrlPart,
  OpenAiContentPart,
  OpenAiToolFunction,
  OpenAiTool,
  OpenAiToolCall,
  OpenAiUsage,
  OpenAiChatRequest,
  OpenAiChatChoice,
  OpenAiChatResponse,
  OpenAiSpeechRequest,
  OpenAiTranscribeRequest,
  OpenAiTranscribeResponse,
  OpenAiTranslateRequest,
  OpenAiTranslateResponse,
  OpenAiEmbeddingRequest,
  OpenAiEmbeddingData,
  OpenAiEmbeddingUsage,
  OpenAiEmbeddingResponse,
  OpenAiImageEditRequest,
  OpenAiImageData,
  OpenAiImageEditUsage,
  OpenAiImageEditResponse,
  OpenAiImageGenerationRequest,
  OpenAiGeneratedImage,
  OpenAiImageGenerationUsage,
  OpenAiImageGenerationResponse,
  OpenAiModerationRequest,
  OpenAiModerationResponse,
  OpenAiModerationResult,
  OpenAiModerationCategories,
  OpenAiModerationCategoryScores,
  OpenAiModerationCategoryAppliedInputTypes,
  OpenAiModerationTextInput,
  OpenAiModerationImageUrlInput,
  OpenAiModerationMultiModalInput,
  OpenAiFile,
  OpenAiFileListRequest,
  OpenAiFileListResponse,
  OpenAiFileUploadRequest,
  OpenAiFileDeleteResponse,
  OpenAiModel,
  OpenAiModelListResponse,
  OpenAiModelDeleteResponse,
  OpenAiBatchCreateRequest,
  OpenAiBatch,
  OpenAiBatchListParams,
  OpenAiBatchListResponse,
  OpenAiBatchRequestCounts,
  OpenAiBatchError,
  OpenAiBatchErrors,
  OpenAiResponseDeleteResponse,
  OpenAiResponseGetOptions,
  OpenAiResponseRequest,
  OpenAiResponseResponse,
  OpenAiResponseInputItem,
  OpenAiResponseInputMessage,
  OpenAiResponseInputContent,
  OpenAiResponseInputTextContent,
  OpenAiResponseInputImageContent,
  OpenAiResponseInputAudioContent,
  OpenAiResponseFunctionCallOutput,
  OpenAiResponseItemReference,
  OpenAiResponseTool,
  OpenAiResponseFunctionTool,
  OpenAiResponseWebSearchTool,
  OpenAiResponseFileSearchTool,
  OpenAiResponseCodeInterpreterTool,
  OpenAiResponseTextFormat,
  OpenAiResponseReasoning,
  OpenAiResponseOutputItem,
  OpenAiResponseOutputMessage,
  OpenAiResponseFunctionCallItem,
  OpenAiResponseWebSearchCallItem,
  OpenAiResponseFileSearchCallItem,
  OpenAiResponseFileSearchResult,
  OpenAiResponseOutputContent,
  OpenAiResponseOutputText,
  OpenAiResponseRefusal,
  OpenAiResponseAnnotation,
  OpenAiResponseUsage,
  OpenAiResponseInputItemsOptions,
  OpenAiResponseInputItemsResponse,
  OpenAiResponseCompactRequest,
  OpenAiResponseCompactResponse,
  OpenAiResponseInputTokensRequest,
  OpenAiResponseInputTokensResponse,
  OpenAiFineTuningJobError,
  OpenAiFineTuningHyperparameters,
  OpenAiFineTuningSupervisedHyperparameters,
  OpenAiFineTuningSupervisedMethod,
  OpenAiFineTuningDpoHyperparameters,
  OpenAiFineTuningDpoMethod,
  OpenAiFineTuningReinforcementHyperparameters,
  OpenAiFineTuningReinforcementMethod,
  OpenAiFineTuningMethod,
  OpenAiFineTuningWandbConfig,
  OpenAiFineTuningIntegration,
  OpenAiFineTuningJob,
  OpenAiFineTuningJobCreateRequest,
  OpenAiFineTuningJobListOptions,
  OpenAiFineTuningJobListResponse,
  OpenAiFineTuningJobEvent,
  OpenAiFineTuningJobEventListOptions,
  OpenAiFineTuningJobEventListResponse,
  OpenAiFineTuningCheckpointMetrics,
  OpenAiFineTuningJobCheckpoint,
  OpenAiFineTuningJobCheckpointListOptions,
  OpenAiFineTuningJobCheckpointListResponse,
  OpenAiCheckpointPermission,
  OpenAiCheckpointPermissionCreateRequest,
  OpenAiCheckpointPermissionCreateResponse,
  OpenAiCheckpointPermissionListOptions,
  OpenAiCheckpointPermissionListResponse,
  OpenAiCheckpointPermissionDeleteResponse,
  OpenAiStoredCompletionListOptions,
  OpenAiStoredCompletionListResponse,
  OpenAiStoredCompletionDeleteResponse,
  OpenAiStoredCompletionUpdateRequest,
  OpenAiStoredCompletionMessage,
  OpenAiStoredCompletionMessageListOptions,
  OpenAiStoredCompletionMessageListResponse,
  OpenAiProvider,
} from "./types";
